apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fiap-todo-api
  namespace: flux-system
spec:
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: fiap-todo-api
  path: ./gitops-repo/applications/fiap-todo-api/overlays/production
  prune: true
  wait: true
  timeout: 2m
  targetNamespace: fiap-todo-prod
