apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: fiap-todo-api
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/cardosolutions/fiap-dclt-aula04
  ref:
    branch: main
  ignore: |
    /*
    !/gitops-repo/applications/
