apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiap-todo-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production

images:
- name: fiap-todo-api
  newName: 497172038820.dkr.ecr.sa-east-1.amazonaws.com/fiap-todo-api
  newTag: 5f2c62505dae3b73a36764fe960b7cc733d877e1
